import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Scene from "~/components/Scene";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>R3F</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <header className="box-border flex min-h-min min-w-full flex-row content-center justify-center justify-items-center border-2 border-white text-center">
          <h1 className="text-center text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            VR <span className="text-[hsl(280,100%,70%)]">Astro</span> Sim
          </h1>
        </header>

        <main className="container flex min-h-fit flex-col items-center justify-start gap-12  border-2 border-blue-500 px-4 py-16">
          <div
            id="canvas-holder"
            className="h-96 min-w-full border-2 border-green-500"
          >
            <Scene />
          </div>

          <div className="grid grid-cols-1 gap-4 border-2 border-red-500 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Gathered by gravity Sea of Tranquility billions upon billions
                birth corpus callosum the only home we've ever known. Something
                incredible is waiting to be known dream of the mind's eye
                intelligent beings take root and flourish vastness is bearable
                only through love cosmic ocean. From which we spring bits of
                moving fluff astonishment a mote of dust suspended in a sunbeam
                astonishment stirred by starlight? Something incredible is
                waiting to be known star stuff harvesting star light hundreds of
                thousands descended from astronomers extraordinary claims
                require extraordinary evidence across the centuries and billions
                upon billions upon billions upon billions upon billions upon
                billions upon billions.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
        </main>
        <footer className="flex min-h-fit min-w-full flex-row border-2 border-white text-white">
          <h2 className="py-2 pl-2">Footer</h2>
        </footer>
      </div>
    </>
  );
};

export default Home;
