import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRef } from 'react';
import Scene from '~/components/Scene';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>R3F</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <header className="box-border flex min-h-min min-w-full flex-row content-center justify-center justify-items-center border-2 border-white text-center">
          <h1 className="text-center text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            VR <span className="text-[hsl(280,100%,70%)]">Astro</span> Sim
          </h1>
        </header>

        <main className="container flex min-h-fit flex-col items-center justify-start gap-12  border-2 border-blue-500 px-4 py-16">
          {/* Canvas */}
          <div
            id="canvas-holder"
            className="h-96 min-w-full border-2 border-white"
          >
            <Scene />
          </div>

          <div className="grid grid-cols-1 gap-4 border-2 border-red-500 sm:grid-cols-2 md:gap-8">
            <div className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce
                vulputate faucibus mollis. Nam lorem nisl, porttitor et
                consequat non, consectetur eget magna. Proin facilisis
                consectetur tellus, at porta leo euismod viverra. Cras vulputate
                nec purus in posuere. Proin at dapibus neque. Maecenas vel orci
                non orci mollis aliquam.
              </div>
            </div>
            <div className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Maecenas congue faucibus dui quis tempor. Proin ut metus est.
                Class aptent taciti sociosqu ad litora torquent per conubia
                nostra, per inceptos himenaeos. Maecenas vel commodo dui. Duis
                sed mi ex.
              </div>
            </div>
          </div>
        </main>
        <footer className="flex min-h-fit min-w-full flex-row border-2 border-white text-white">
          <h2 className="py-2 pl-2">Footer</h2>
        </footer>
      </div>
    </>
  );
};

export default Home;
